import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const url=process.env.TEST_URL||'http://localhost:4175/';
const browser=await chromium.launch({channel:'msedge',headless:true});
fs.mkdirSync('test-results',{recursive:true});
const report={url,checks:[],errors:[]};
const sizes=[{width:1440,height:900},{width:390,height:844},{width:320,height:568},{width:844,height:390}];
const track=p=>{p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`);});};
const start=async p=>{await p.goto(url);await p.locator('[data-panel=settings]').first().click();await p.locator('input[type=checkbox]').check();await p.locator('#close-panel').click();await p.locator('#new-game').click();};
try{
 for(const size of sizes){const ctx=await browser.newContext({viewport:size,deviceScaleFactor:1});const p=await ctx.newPage();track(p);await p.goto(url);await p.locator('#new-game').waitFor();await p.evaluate(async()=>{const im=new Image();im.src='assets/manor.png';await im.decode();});await p.screenshot({path:`test-results/title-${size.width}.png`,fullPage:true});assert.equal(await p.locator('#title-screen ruby').count(),0);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await start(p);await p.locator('#dialogue').click();assert.ok((await p.locator('#text').evaluate(n=>{const c=n.cloneNode(true);c.querySelectorAll('rt').forEach(r=>r.remove());return c.textContent;})).includes('私を弔いに来て'));
  const seeded=await p.evaluate(async()=>{const e=await import('./src/engine.js');const d=JSON.parse(localStorage.getItem('choushou.v1'));const s=e.fresh();s.node='threshold';s.line=1;d.auto={state:s,date:new Date().toISOString(),label:'test'};return d;});await p.addInitScript(d=>localStorage.setItem('choushou.v1',JSON.stringify(d)),seeded);await p.reload();await p.locator('#continue-game').click();await p.locator('#portrait').evaluate(im=>im.decode());assert.ok(await p.locator('#text ruby').count()>0);assert.equal(await p.locator('#speaker-box ruby').count(),0);await p.screenshot({path:`test-results/ruby-${size.width}.png`,fullPage:true});
  await p.locator('[data-panel=settings]').filter({visible:true}).click();await p.locator('#setting-fontSize').fill('30');await p.locator('#close-panel').click();await p.screenshot({path:`test-results/ruby-large-${size.width}.png`,fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.checks.push(`title, ruby, nameplate, large font, layout ${size.width}x${size.height}`);await ctx.close();
 }
 const ctx=await browser.newContext({viewport:sizes[0]});const p=await ctx.newPage();track(p);await start(p);
 for(let i=0;i<8;i++)await p.locator('#dialogue').click();const savedText=await p.locator('#text').textContent();await p.locator('[data-panel=save]').click();await p.locator('.slot').first().click();await p.locator('#close-panel').click();await p.locator('#dialogue').click();await p.locator('[data-panel=load]').filter({visible:true}).click();await p.locator('.slot').filter({hasText:'記録 01'}).click();await p.getByRole('button',{name:'進める',exact:true}).click();assert.equal(await p.locator('#text').textContent(),savedText);
 await p.locator('[data-panel=backlog]').click();assert.ok(await p.locator('.log-item ruby').count()>0);await p.locator('#close-panel').click();await p.locator('#skip').click();await p.waitForTimeout(200);assert.equal(await p.locator('#skip').getAttribute('aria-pressed'),'false');
 await p.locator('#menu-button').click();await p.getByRole('button',{name:'引き継ぎ',exact:true}).filter({visible:true}).click();await p.getByRole('button',{name:'コードを発行',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#export-code').value.startsWith('CHOU1'));const code=await p.locator('#export-code').inputValue();const qr=await p.locator('.qr-wrap img').getAttribute('src');const qrData=Buffer.from(qr.split(',')[1],'base64');await p.locator('#qr-file').setInputFiles({name:'qr.gif',mimeType:'image/gif',buffer:qrData});await p.waitForFunction(()=>document.querySelector('#import-code').value.startsWith('CHOU1'));assert.equal(await p.locator('#import-code').inputValue(),code);report.checks.push('manual save/load, ruby backlog, unread skip stop, transfer export and QR decode');
 const cx2=await browser.newContext(),p2=await cx2.newPage();track(p2);await p2.goto(url);await p2.locator('[data-panel=transfer]').click();await p2.locator('#import-code').fill(code);await p2.getByRole('button',{name:'コードを確かめる'}).click();await p2.getByRole('button',{name:'進める',exact:true}).click();await p2.locator('#dialogue').click();assert.ok(await p2.locator('#game-screen').isVisible());report.checks.push('transfer in independent browser with default typing');await cx2.close();await ctx.close();
 // Traverse every displayed line through production click handlers, while independently tracking engine state.
 for(const [name,choice]of Object.entries({morning:1,rain:0,cage:-1})){
 const cx=await browser.newContext({viewport:name==='rain'?sizes[1]:sizes[0]});const page=await cx.newPage();track(page);await start(page);
 const result=await page.evaluate(async choice=>{const e=await import('./src/engine.js'),s=e.fresh();let paragraphs=0;while(paragraphs<2000){const n=e.story[s.node];for(let i=0;i<n.lines.length;i++){const clone=document.querySelector('#text').cloneNode(true);clone.querySelectorAll('rt').forEach(rt=>rt.remove());if(clone.textContent!==n.lines[i].text)throw Error('Text mismatch '+n.id+':'+i);paragraphs++;if(i<n.lines.length-1)document.querySelector('#dialogue').click();}
 s.line=n.lines.length-1;e.finishNode(s);if(n.ending){document.querySelector('#dialogue').click();return {ending:n.ending,paragraphs,seen:JSON.parse(localStorage.getItem('choushou.v1')).meta.seen.length};}
 const choices=e.getChoices(s);if(choices.length){let i=0;if(n.id==='theory')i=2;if(n.id==='before_choice')i=choice===-1?1:0;if(n.id==='doctor_offer')i=choice;if(n.id==='arrival')i=choice===0?1:0;const buttons=document.querySelectorAll('#choices button');if(buttons[i].disabled)throw Error('Disabled '+n.id);buttons[i].click();e.choose(s,i);}else{document.querySelector('#dialogue').click();e.applyNode(s,e.nextNode(s));}
 if(paragraphs%100<20)await new Promise(r=>setTimeout(r,0));}throw Error('route runaway');},choice);
 assert.equal(result.ending,name);assert.ok(await page.locator('#ending-screen').isVisible());await page.screenshot({path:`test-results/ending-${name}.png`,fullPage:true});await page.locator('#ending-title').click();await page.locator('[data-panel=endings]').first().click();assert.equal(await page.locator('.ending-item details').count(),1);report.checks.push(result);await cx.close();
 }
 assert.deepEqual(report.errors,[]);console.log(JSON.stringify(report,null,2));
}finally{fs.writeFileSync('test-results/browser-report.json',JSON.stringify(report,null,2));await browser.close();}

